apiVersion: v1
kind: Service
metadata:
  name: example1
  labels:
    app: example1  
spec:
  type: NodePort
  selector:
      app: example1
  ports:
    - protocal: TCP
      targetPort: 80
      port: 80
      nodePort: 30080